# Generated by Django 4.2 on 2023-07-30 07:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField()),
                ('longitude', models.FloatField(max_length=100)),
                ('latitude', models.FloatField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, message='Value must be greater than or equal to 1.'), django.core.validators.MaxValueValidator(5, message='Value must be less than or equal to 5.')])),
                ('avg_rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='destinationPlanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postid', models.UUIDField(default=uuid.uuid4)),
                ('budget', models.FloatField(default=0)),
                ('no_of_people', models.IntegerField(default=0)),
                ('no_of_days', models.IntegerField(default=0)),
                ('purpose_of_visit', models.CharField(blank=True, choices=[('Bussiness', 'BUSSINESS'), ('Explore', 'EXPLORE'), ('Holidays', 'HOLIDAYS'), ('Religious Tour', 'RELIGIOUS TOUR'), ('Personal Work', 'PERSONAL WORK')], default='', max_length=100)),
                ('description', models.TextField()),
                ('date_of_visit', models.DateField()),
                ('visitCompleted', models.BooleanField(default=False)),
                ('MoneySpent', models.IntegerField(default=0)),
                ('tips', models.CharField(max_length=500)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.destination')),
            ],
        ),
    ]
