# Generated by Django 4.2 on 2023-07-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_destinationplanner_moneyspent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationplanner',
            name='tips',
            field=models.CharField(blank=True, default=' ', max_length=500, null=True),
        ),
    ]
