# Generated by Django 4.2 on 2023-07-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_alter_destinationplanner_tips'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationplanner',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
