# Generated by Django 4.2 on 2023-07-31 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_destinationplanner_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationplanner',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.destination'),
        ),
    ]
